config/routes.rb
Rails.application.routes.draw do
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :information, dependent: :destroy
  accepts_nested_attributes_for :information,
                                 # 削除フラグで削除できるようにする
                                 allow_destroy: true,
                                 # いずれかが未入力なら登録しない
                                 reject_if: lambda{|attributes| attributes[:introduction].blank? || attributes[:height].blank? || attributes[:hobby].blank? || attributes[:favorite].blank?}

  # Active Storage
  has_many_attached :images

  validates :name_ja, :name_en, :name_gun, presence: true #同名でも別銃の場合があるので同名可
  validate  :gun_category #古銃か現代銃かのみ選択
  before_validation :character_sprit #入力値前後スペース除去

  private

  def gun_category
    x = self.gun_category_id
    unless x == 1 || x == 2
      errors.add(:gun_category_id, "Please select")
    end
  end

  def character_sprit
    self.name_ja.strip!
    self.name_en.strip!
    self.name_gun.strip!
    self.motif.strip!
  end

  # 条件ごとに検索をscope設定
  # キーワード検索/ActiveRecord::Relation 維持
  scope :keyword, ->(keyword) do
    where(<<-SQL, keyword: "%#{keyword}%")
      name_ja LIKE :keyword
      OR name_en LIKE :keyword
      OR name_gun LIKE :keyword
      OR motif LIKE :keyword
      SQL
  end

  scope :gun_category, -> (category){ where(gun_category_id: category) if category.present? }
  scope :gun_type, -> (gun_type){ where(gun_type_id: gun_type) if gun_type.present? }
  scope :country, -> (country){ where(country_id: country) if country.present? }
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  #ヘルパーにメソッドを引き渡す
  helper_method :sort_column, :sort_direction

  # GET /characters
  # GET /characters.json
  def index
    keyword = params[:keyword].present? ? params[:keyword] : nil
    category = params[:gun_category].present? ? params[:gun_category][:gun_category_id] : nil
    gun_type = params[:gun_type].present? ? params[:gun_type] : nil
    country = params[:country].present? ? params[:country] : nil
    @characters = Character
                    .keyword(keyword)
                    .gun_category(category)
                    .gun_type(gun_type)
                    .country(country)
                    .order(sort_column => sort_direction)
                    .with_attached_images.page(params[:page]).per(5)
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @gun_category = GunCategory.find(@character.gun_category_id).name
    @gun_type = GunType.find(@character.gun_type_id).name
    @country = Country.order(:id).find(@character.country_id).name
    @information = @character.information.order(:title_id) #千銃士/千銃士Rの順にする
  end

  # GET /characters/new
  def new
    @character = Character.new
    2.times{@character.information.build}
  end

  # GET /characters/1/edit
  def edit
    if @character.information.count == 0
      2.times{@character.information.build}
    else
      @character.information.build if @character.information.count == 1
    end
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    #チェック入り画像は削除する
     if params[:character][:image_ids].present?
       ids = params[:character][:image_ids]
       ids.each do |id|
         image = @character.images.find(id)
         image.purge
       end
     end

    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.images.purge #紐づいている画像も削除
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(
        :name_ja,
        :name_en,
        :name_gun,
        :gun_category_id,
        :gun_type_id,
        :country_id,
        :motif,
        # Active Storageの画像用パラメータ
        images: [],
        # 無印とRの情報
        information_attributes: [
          :id,
          :character_id,
          :title_id,
          :introduction,
          :height,
          :hobby,
          :favorite,
          # チェックボックスで_destroyチェック入りなら削除になる
          :_destroy
        ]
      )
    end

    #ソート対象カラムメソッド
    def sort_column
      #ソート対象カラムのホワイトリスト
      %w[name_ja name_en name_gun].include?(params[:column]) ? params[:column] : :id
    end

    #ソートasc/desc判定
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
end

app/helpers/characters_helper.rb
module CharactersHelper

  # ソート用メソッド
  def sort_order(column, title, hash_params = {})
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { column: column, direction: direction }.merge(hash_params), class: "sort_header #{css_class}"
  end

end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :images %>
      <% if form.object.images.present? %>
        <div>
          <%= "削除したい画像はチェックを入れる" %>
        </div>
        <% form.object.images.each do |image| %>
          <div class="side-by-side">
            <%= image_tag image, class: "image-size" %>
            <%= form.check_box :image_ids, {multiple: true}, image.id, false %>
          </div>
        <% end %>
      <% end %>
    <div>
      <%= form.file_field :images, multiple: true %>
    </div>
    <!-- 画像プレビュー -->
    <div id="image_preview"></div>
  </div>

  <div class="field">
    <%= form.label :name_ja %>
    <div class="text-field">
      <div class="width-resize-dummy js-dummy-width-resize" data-placeholder=<%= t ".name_ja" %>></div>
      <%= form.text_field :name_ja,
                          onkeydown: "KeyDown('name', 'ja')",
                          onclick: "ClearButtonDisplay('name', 'ja'), PasteCheck('name', 'ja')",
                          class: "width-resize js-width-resize",
                          placeholder: t(".name_ja") %>
      <!-- クリアボタン -->
      <div id="name-ja-clear" class="clear-button fas fa-times" onclick="InputClear('name', 'ja')">
        <!-- ツールチップ -->
        <div class="form-clear-balloon"><%= t "views.form.clear" %></div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :name_en %>
    <div class="text-field">
      <div class="width-resize-dummy js-dummy-width-resize" data-placeholder="英語名入力"></div>
      <%= form.text_field :name_en,
                          onkeydown: "KeyDown('name', 'en')",
                          onclick: "ClearButtonDisplay('name', 'en'), PasteCheck('name', 'en')",
                          class: "width-resize js-width-resize",
                          placeholder: t(".name_en") %>
      <!-- クリアボタン -->
      <div id="name-en-clear" class="clear-button fas fa-times" onclick="InputClear('name', 'en')">
        <!-- ツールチップ -->
        <div class="form-clear-balloon"><%= t "views.form.clear" %></div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :name_gun %>
    <div class="text-field">
      <div class="width-resize-dummy js-dummy-width-resize" data-placeholder="モチーフ名入力"></div>
      <%= form.text_field :name_gun,
                          onkeydown: "KeyDown('name', 'gun')",
                          onclick: "ClearButtonDisplay('name', 'gun'), PasteCheck('name', 'gun')",
                          class: "width-resize js-width-resize",
                          placeholder: t(".name_gun") %>
      <!-- クリアボタン -->
      <div id="name-gun-clear" class="clear-button fas fa-times" onclick="InputClear('name', 'gun')">
        <!-- ツールチップ -->
        <div class="form-clear-balloon"><%= t "views.form.clear" %></div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :gun_category_id %>
    <div class="radio-button-form">
      <%= form.collection_radio_buttons :gun_category_id, GunCategory.all, :id, :name, form.object.gun_category_id.blank? ? {checked: 1} : {checked: form.object.gun_category_id} %>
    </div>
  </div>

  <div class="field">
    <%= form.label :gun_type_id %>
    <%= form.collection_select(:gun_type_id, GunType.order(:ruby), :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.collection_select(:country_id, Country.order(:ruby), :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :motif %>
    <div class="text-area">
      <%= form.text_area :motif,
                         onkeydown: "KeyDown('motif')",
                         onclick: "ClearButtonDisplay('motif'), PasteCheck('motif')",
                         placeholder: t(".motif") %>
      <!-- クリアボタン -->
      <div id="motif-clear" class="clear-button fas fa-times" onclick="InputClear('motif')">
        <!-- ツールチップ -->
        <div class="form-clear-balloon"><%= t "views.form.clear" %></div>
      </div>
    </div>
  </div>

  <%= form.fields_for :information do |i| %>
    <%= render "information_form", form: i %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= javascript_include_tag "characters/form" %>

app/views/characters/_information_form.html.erb
  <%= form.hidden_field :character_id, value: params[:id] %>
  <!-- クリアボタン用ID取得 / 関数内で引き渡す -->
  <% @info_index = form.index %>

  <!-- 新規作成なら削除ボックス非表示 -->
  <% if form.object.id.present? %>
    <div>
      <%= "削除対象はチェックを入れる" %>
      <%= form.check_box "_destroy" %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title_id %>
    <div class="radio-button-form">
      <%= form.collection_radio_buttons :title_id, Title.all, :id, :name, form.object.title_id.blank? ? {checked: 1} : {checked: form.object.title_id} %>
    </div>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <div class="text-area">
      <%= form.text_area :introduction,
                         onkeydown: "KeyDown(#{@info_index}, 'introduction')",
                         onclick: "ClearButtonDisplay(#{@info_index}, 'introduction'), PasteCheck(#{@info_index}, 'introduction')",
                         placeholder: t(".introduction") %>
      <!-- クリアボタン -->
      <div id="introduction-<%= @info_index %>-clear" class="clear-button fas fa-times" onclick="InputClear(<%= @info_index %>, 'introduction')">
        <!-- ツールチップ -->
        <div class="form-clear-balloon"><%= t "views.form.clear" %></div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.select :height, [*140..200] %> cm
  </div>

  <div class="field">
    <%= form.label :hobby %>
    <div class="text-field">
      <div class="width-resize-dummy js-dummy-width-resize" data-placeholder=<%= t ".hobby" %>></div>
      <%= form.text_field :hobby,
                          onkeydown: "KeyDown(#{@info_index}, 'hobby')",
                          onclick: "ClearButtonDisplay(#{@info_index}, 'hobby'), PasteCheck(#{@info_index}, 'hobby')",
                          class: "width-resize js-width-resize",
                          placeholder: t(".hobby") %>
      <!-- クリアボタン -->
      <div id="hobby-<%= @info_index %>-clear" class="clear-button fas fa-times" onclick="InputClear(<%= @info_index %>, 'hobby')">
        <!-- ツールチップ -->
        <div class="form-clear-balloon"><%= t "views.form.clear" %></div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :favorite %>
    <div class="text-field">
      <div class="width-resize-dummy js-dummy-width-resize" data-placeholder=<%= t ".favorite" %>></div>
      <%= form.text_field :favorite,
                          onkeydown: "KeyDown(#{@info_index}, 'favorite')",
                          onclick: "ClearButtonDisplay(#{@info_index}, 'favorite'), PasteCheck(#{@info_index}, 'favorite')",
                          class: "width-resize js-width-resize",
                          placeholder: t(".favorite") %>
      <!-- クリアボタン -->
      <div id="favorite-<%= @info_index %>-clear" class="clear-button fas fa-times" onclick="InputClear(<%= @info_index %>, 'favorite')">
        <!-- ツールチップ -->
        <div class="form-clear-balloon"><%= t "views.form.clear" %></div>
      </div>
    </div>
  </div>

app/views/characters/edit.html.erb
<h1><%= t ".title" %></h1>

<%= render 'form', character: @character %>

<%= link_to character_path(@character, take_params) do %>
  <i class="fas fa-info-circle"></i>
<% end %>
 |
<%= link_to characters_path(take_params) do %>
  <i class="fas fa-reply"></i>
<% end %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t ".title" %></h1>

<!-- ここから検索フィールド -->
<div class="search-field-wrap">
  <%= form_with url: characters_path, method: :get, local: true do %>
    <div class="text-field">
      <%= text_field_tag :keyword,
                         params[:keyword],
                         placeholder: t(".keyword"),
                         onkeydown: "SearchFieldKeyDown()",
                         onclick: "KeywordClearDisplay()" %>
      <div id="search-field-clear" class="clear-button fas fa-times" onclick="KeywordClearButton()">
        <!-- ツールチップ -->
        <div class="search-clear-balloon"><%= t "views.form.clear" %></div>
      </div>
    </div>
    <div class="radio-buttons">
      <%= collection_radio_buttons(:gun_category, :gun_category_id, GunCategory.all, :id, :name, params[:gun_category].blank? ? {checked: false} : {checked: params[:gun_category][:gun_category_id]}) %>
    </div>
    <%= select_tag(:gun_type, options_from_collection_for_select(GunType.order(:ruby), :id, :name, selected: params[:gun_type]), {include_blank: t(".gun_type")}) %>
    <%= select_tag(:country, options_from_collection_for_select(Country.order(:ruby), :id, :name, selected: params[:country]), {include_blank: t(".country")}) %>
    <%= submit_tag "Search" %>
    <%= link_to characters_path do %>
      <%= button_tag "Reset" %>
    <% end %>
  <% end %>
</div>
<!-- ここまで検索フィールド -->

<div>
  <%= paginate @characters %>
</div>

<table class="cell-width-setting"><!-- 列の幅設定 -->
  <thead>
    <tr>
      <!-- ここからソート用変数 -->
      <!-- gun_category_idはハッシュ形式で変数に格納する -->
      <% @gun_category = params[:gun_category].blank? ? nil : {gun_category_id: params[:gun_category][:gun_category_id] } %>
      <!-- sort_orderに渡す検索対象カラム -->
      <% @search_theme = {keyword: params[:keyword], gun_category: @gun_category, gun_type: params[:gun_type], country: params[:country]} %>
      <!-- ここまでソート用変数 -->
      <th class="sort-link">
        <%= sort_order "name_ja", t(".name_ja"), @search_theme %>
        <!-- ツールチップ -->
        <div class="sort-link-width-setting">
          <div class="sort-link-balloon"><%= t("views.sort.name_ja") %></div>
        </div>
      </th>
      <th class="sort-link">
        <%= sort_order "name_en", t(".name_en"), @search_theme %>
        <!-- ツールチップ -->
        <div class="sort-link-width-setting">
          <div class="sort-link-balloon"><%= t("views.sort.name_en") %></div>
        </div>
      </th>
      <th class="sort-link">
        <%= sort_order "name_gun", t(".name_gun"), @search_theme %>
        <!-- ツールチップ -->
        <div class="sort-link-width-setting">
          <div class="sort-link-balloon"><%= t("views.sort.name_gun") %></div>
        </div>
      </th>
      <th></th>
      <th>Gun category</th>
      <th>Gun type</th>
      <th>Country</th>
      <th class="cell-width-motif"><%= t ".motif" %></th>
      <th colspan="3" class="cell-width-icon">Do</th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name_ja %></td>
        <td><%= character.name_en %></td>
        <td><%= character.name_gun %></td>
        <td>
          <% if character.images.present? %>
            <%= image_tag character.images.first, class: "top-thumbnail" %>
          <% end %>
        </td>
        <td><%= character.gun_category_id %></td>
        <td><%= character.gun_type_id %></td>
        <td><%= character.country_id %></td>
        <td><%= character.motif %></td>
        <td class="tooltip-icon">
          <!-- take_paramsメソッドで検索条件保持 -->
          <%= link_to character_path(character, take_params) do %>
            <i class="fas fa-info-circle"></i>
          <% end %>
          <!-- ツールチップ -->
          <div class="tooltip-icon-balloon tooltip-design-show"><%= t("views.icon.show") %></div>
        </td>
        <td class="tooltip-icon">
          <%= link_to edit_character_path(character, take_params) do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <!-- ツールチップ -->
          <div class="tooltip-icon-balloon tooltip-design-edit"><%= t("views.icon.edit") %></div>
        </td>
        <td class="tooltip-icon">
          <%= link_to character, method: :delete, data: { confirm: t(".message", name_ja: character.name_ja) } do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
          <!-- ツールチップ -->
          <div class="tooltip-icon-balloon tooltip-design-destroy"><%= t("views.icon.delete") %></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_character_path(take_params) do %>
  <i class="fas fa-plus-square fa-lg"></i>
<% end %>

<script>
  // オートコンプリート
  window.addEventListener('keydown', function(){
    data = <%== Character.pluck(:name_ja, :name_en, :name_gun).flatten.uniq %>;
    $("#keyword").autocomplete({
      // 前方一致で候補を表示
      source: function(request, response) {
        response(
          $.grep(data, function(value){
            return value.indexOf(request.term) === 0;
          })
        );
      }
    });
  });
</script>
<%= javascript_include_tag "characters/index" %>

app/views/characters/new.html.erb
<h1><%= t ".title" %></h1>

<%= render 'form', character: @character %>

<%= link_to characters_path(take_params) do %>
  <i class="fas fa-reply"></i>
<% end %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<!-- imagesがblankならスライダー自体表示しない -->
<% if @character.images.present? %>
  <div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
      <!-- Slides -->
      <% @character.images.each do |i| %>
        <div class="swiper-slide image-layout">
          <!-- クリックで画像拡大 -->
          <%= link_to i, "data-lightbox": i do %>
            <%= image_tag i, class: "image-size" %>
          <% end %>
        </div>
      <% end %>
    </div>

    <!-- imagesが2件以上ならボタン表示 -->
    <% if @character.images.count > 1 %>
      <!-- If we need pagination -->
      <div class="swiper-pagination"></div>

      <!-- If we need navigation buttons -->
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>

      <!-- If we need scrollbar -->
      <div class="swiper-scrollbar"></div>
    <% end %>
  </div>
<% end %>

<p>
  <strong><%= t ".name_ja" %></strong>
  <%= @character.name_ja %>
</p>

<p>
  <strong><%= t ".name_en" %></strong>
  <%= @character.name_en %>
</p>

<p>
  <strong><%= t ".name_gun" %></strong>
  <%= @character.name_gun %>
</p>

<p>
  <strong><%= t ".gun_category" %></strong>
  <%= @gun_category %>
</p>

<p>
  <strong><%= t ".gun_type" %></strong>
  <%= @gun_type %>
</p>

<p>
  <strong><%= t ".country" %></strong>
  <%= @country %>
</p>

<div class="tab-wrap">
  <input id="tab-character-<%= @character.id %>" type="radio" name="TAB" class="tab-switch" checked="checked" />
  <label class="tab-label" for="tab-character-<%= @character.id %>">MOTIF</label>
  <div class="tab-content">
    <%= simple_format(h(@character.motif)) %>
  </div>
  <% @information.each do |i| %>
    <% if @character.information.any? %>
      <input id="tab-information-<%= i.id %>" type="radio" name="TAB" class="tab-switch" />
      <label class="tab-label" for="tab-information-<%= i.id %>">
        <%= Title.find(i.title_id).name %>
      </label>
      <div class="tab-content">
        <p>
          <strong><%= t ".introduction" %></strong>
          <%= simple_format(h(i.introduction)) %>
        </p>

        <p>
          <strong><%= t ".height" %></strong>
          <%= i.height %> cm
        </p>

        <p>
          <strong><%= t ".hobby" %></strong>
          <%= i.hobby %>
        </p>

        <p>
          <strong><%= t ".favorite" %></strong>
          <%= i.favorite %>
        </p>
      </div>
    <% end %>
  <%end%>
</div>

<%= link_to edit_character_path(@character) do %>
  <i class="fas fa-edit"></i>
<% end %>
 |
<!-- take_paramsメソッドで検索条件保持 -->
<%= link_to characters_path(take_params) do %>
  <i class="fas fa-reply"></i>
<% end %>

<!-- swiper設置 -->
<%= javascript_include_tag "characters/show" %>